### ISSUE TITLE
where to find the two files, thanks.

### ISSUE THREAD

**Issue by liamxg** [flu-crew/H3_risk_pipeline#1]
<img width="1005" alt="image" src="https://github.com/flu-crew/h3-risk-pipeline/assets/46078579/86cdb512-4475-4afb-add6-6dc658035983">

**Comment by liamxg** [comment]
@j23414 @Nicolaaht

**Comment by tkanderson** [comment]
@liamxg The data are in the supplemental directory: https://github.com/flu-crew/h3-risk-pipeline/tree/main/supplementary-data the tables are just titled differently.
